<?php

if (!defined('ABSPATH'))
	exit("No script kiddies");

#Do not edit this file

return array(
	"id" => "wc_hubtelpayment",
	"icon" => plugin_dir_url(__FILE__) . "../assets/images/logo.png",
	"title" => "Hubtel Payment",
	"description" => "Integrate credit card, debit card and mobile money payment into your Woocommerce site.",
	"supported_currency" => "GHS,NGN,USD,EUR,GBP",
	"payment_successful" => "Thank you for shopping with us, your payment was succssful. You order is currently beign processed. Your Order id is ",
	"payment_failed" => "Thank you for shopping with us. However, the transaction could not be completed.",
	"payment_session" => "Thank you for shopping with us. Howerever, Your transaction session timed out. Your Order id is ",
	"email_notification" => "Thank you for shopping with us. However, Your transaction session timed out. Your Order id is ",
	"payment_endpoint" => "https://api.hubtel.com/v1/merchantaccount/onlinecheckout/invoice/create",
	"response_endpoint" => "https://api.hubtel.com/v1/merchantaccount/onlinecheckout/invoice/status/",
	"license_baseapi" => "http://iportal.mobicongroup.com/invitasio/index.php/api/",
	"clientid" => "",
	"secret" => "",
	"emails" => "",
	);
